### ISSUE TITLE
java.lang.IllegalStateException: cannot find symbol

### ISSUE THREAD

**Issue by oleksandr** [dneves/thrift-ui-fx#2]
Trying out the tool on OSX with

```
thrift --version
Thrift version 0.10.0

java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

leads to

```
8.982 [JavaFX Application Thread] DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the context classpath (config.properties)
13:20:28.982 [JavaFX Application Thread] DEBUG o.a.c.c.PropertiesConfiguration - Base path set to jar:file:/Users/oleksandr/Projects/3rdParty/thrift-ui-fx/target/jfx/app/thrift-ui-fx-jfx.jar!/config.properties
13:20:47.454 [JavaFX Application Thread] DEBUG com.neon.thrift.ui.gen.CodeGenerator - command: [thrift, -out, /var/folders/k2/w66x0cc12g31p353c_zbkc1w0000gn/T/thrift-BaseService-5900001474768747029, --gen, java, /Users/oleksandr/Projects/shared/api-contracts/thrift/demo.thrift]
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: cannot find symbol
  symbol:   class TSerializable
  location: package org.apache.thrift
          org.apache.thrift.TSerializable msg;
    cannot find symbol
  symbol:   class TSerializable
  location: package org.apache.thrift
          org.apache.thrift.TSerializable msg;

	at org.abstractmeta.toolbox.compilation.compiler.impl.JavaSourceCompilerImpl.compile(JavaSourceCompilerImpl.java:102)
	at org.abstractmeta.toolbox.compilation.compiler.impl.JavaSourceCompilerImpl.compile(JavaSourceCompilerImpl.java:78)
	at org.abstractmeta.toolbox.compilation.compiler.impl.JavaSourceCompilerImpl.compile(JavaSourceCompilerImpl.java:72)
```

Using this simple Thrift file:

```
/**
 * Base service with shared methods
 */
service BaseService {
    /**
     * Health checking routine
     */
    void ping(),
    /**
     * Version checking routine
     */
    map<string,string> getVersion()
}
```

**Comment by dneves** [comment]
Hi

thrift-ui-fx is built with libthrift 0.9.3
try to bump its version to your 0.10.0 in pom.xml and build again - see if
this works.


Thank you,

Diogo Neves

2017-08-02 12:23 GMT+01:00 Oleksandr Lobunets <notifications@github.com>:

**Comment by oleksandr** [comment]
Yes, that worked. Thanks!
